# Generated by Django 4.2.6 on 2023-10-24 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacoesSensiveis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(max_length=25)),
                ('identidade', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='telefone',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='InformacoesSensiveis',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.informacoessensiveis'),
        ),
    ]
