# Generated by Django 4.2.6 on 2023-10-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_informacoessensiveis_alter_pessoas_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='telefone',
            field=models.IntegerField(null=True),
        ),
    ]
